C STUB xxword
      SUBROUTINE XXWORD(STR, IDELIM, NFIRST, MSHORT, IFIRST, ILAST, NW)
      CHARACTER*(*) STR, IDELIM
      INTEGER NFIRST, MSHORT, IFIRST(*), ILAST(*), NW
      NW = 0
      RETURN
      END
