module tx_sol
  implicit none

contains

!***************************************************************
!
!  Calculate SOL coefficients
!
!***************************************************************

  subroutine tx_sol_coefficients

    call tx_sol_parallel_loss
    call tx_sol_particle_balance

  end subroutine tx_sol_coefficients

!***************************************************************
!
!  Calculate parallel losses
!
!  < output >
!   * Frequencies of parallel loss of 
!       particles : rNuL
!       heat      : rNuLTs
!       fast ions : rNuLB
!     in unit of [1/s].
!
!***************************************************************

  subroutine tx_sol_parallel_loss
    use tx_commons, only : NRA, NRMAX, achg, Var, rKilo, amas, amqp, PI, Q, RR, rpt, ra &
         &               , rNuL, FSLP, EPS0, amp, AEE, Zeff, rNuLTs, FSLTs, PTsV_FIX, rKeV &
         &               , PNsV_FIX, NSM, FSLPB, BphV, rNuLB, bbt, BUbparV
    use mod_coulomb, only : coulog
    integer(4) :: NR, i
    real(8) :: PTiVA, DBW, Cs, Lc, RL, Chicl, UbparaL, BBL, gsmth

    ! Initialize

    rNuL(:NRA-1)     = 0.d0
    rNuLTs(:NRA-1,:) = 0.d0
    rNuLB(:NRA-1)    = 0.d0

    ! Banana width at separatrix
!    PTiVA = Var(NRA,2)%T
    PTiVA = 0.5d0 * Var(0,2)%T
    DBW = 3.d0 * sqrt(PTiVA * rKeV * (amas(2)*amp)) * Q(NRA) / (achg(2) * AEE * BphV(NRA)) &
         & / sqrt(ra / RR)

    !     *** Loss to divertor plasma region ***

    ! Calculate only in the SOL plasma

!    IF (rpt(NR) + DBW > ra) THEN
    do NR = NRA, NRMAX
       BBL   = sqrt(bbt(NR))

       ! --- Parallel loss of particles ---
!       Cs = sqrt(2.d0 * Var(NR,1)%T * rKilo / amas(2) / amqp)
       Cs = sqrt((achg(2) * Var(NR,1)%T + 3.d0 * Var(NR,2)%T) * rKilo / (amas(2) * amqp))
       Lc = 2.d0 * PI * Q(NR) * RR ! Connection length to the divertor
       RL = (rpt(NR) - ra) / DBW! / 2.d0
       gsmth = RL**2 / (1.d0 + RL**2)
       rNuL  (NR) = FSLP  * Cs / Lc * gsmth

       ! --- Parallel loss of heat ---
       ! Classical heat conduction [s**4/(kg**2.5*m**6)]
       ! (C S Pitcher and P C Stangeby, PPCF 39 (1997) 779)
       Chicl = (4.d0*PI*EPS0)**2 &
            & /(  sqrt(amas(1)*amp)*AEE**4*Zeff(NR) &
            &   * coulog(Zeff(NR),Var(NR,1)%n,Var(NR,1)%T,Var(NR,2)%T,amas(1),achg(1),amas(2),achg(2)))

       ! When calculating rNuLTs(1), we fix Var(:,1)%n and Var(:,1)%T constant during iteration
       !   to obain good convergence.
       rNuLTs(NR,1) = FSLTs(1) * Chicl * (PTsV_FIX(NR,1)*rKeV)**2.5d0 &
            &                  /(Lc**2 * PNsV_FIX(NR,1)*1.d20) * gsmth
       do i = 2, NSM
          rNuLTs(NR,i) = FSLTs(i) * Cs / Lc * gsmth
       end do

       ! --- Parallel loss of fast ions ---
!       IF(abs(FSRP) > 0.d0) THEN
       UbparaL = BUbparV(NR) / BBL
!!$       IF(NR == NRMAX) Ubpara(NR) = AITKEN2P(rpt(NRMAX), &
!!$            & Ubpara(NRMAX-1),Ubpara(NRMAX-2),Ubpara(NRMAX-3),&
!!$            & rpt(NRMAX-1),rpt(NRMAX-2),rpt(NRMAX-3))
       UbparaL = max(UbparaL, FSLP*Cs)
       rNuLB(NR) = FSLPB * UbparaL / Lc * gsmth
!       END IF
    end do

  end subroutine tx_sol_parallel_loss

!***************************************************************
!
!  Calculate coefficients w.r.t. global particle balance
!    between SOL upstream plasma, divertor plasma and divertor plate
!
!  < output >
!     rGamm0
!     rGamm0zz
!     rGamm0iz
!   * They are overwrittn by rGamm0**_in in case that rGamm0**_in >= 0.
!
!  < interim >
!   * c1(blk/imp)
!     Probability that one bulk neutral generated by recycling
!     on a divertor target runs away throught the divertor plasma
!     region and finally reaches the SOL upstream region
!
!   * c5(blk/imp)
!     Probability that one bulk neutral generated on a divertor
!     target is exhausted by a pump.
!
!   * c3(blk/imp)
!     Inflow flux multiplication factor on a divertor plate
!       c3bkl = 1 / ( c1blk + c5blk )
!
!   * yzz
!     Yield of impurity sputtering by impurities
!       yzz = yzzrefl + yzzphyssput
!
!   * yzzrefl
!     Reflection rate (Z^{*+} -> Z^0) : Z means impurity species.
!
!   * yzzphyssput
!     Self physical sputtering yield (Z^{*+} -> Z^0)
!
!   * yizphyssput
!     Yield of impurity physical sputtering by bulk ions (D^+ -> Z^0)
!
!   * yizchemsput
!     Yield of impurity chemical sputtering by bulk ions (D^+ -> Z^0)
!
!   see pages 3-31 and 3-32 of Homma's notes
!
!***************************************************************
  
  subroutine tx_sol_particle_balance
    use tx_commons, only : rGamm0_in, rGamm0zz_in, rGamm0iz_in, rGamm0, rGamm0zz, rGamm0iz, FSG0iz
    real(8) :: c1blk, c3blk, c5blk, c1imp, c3imp, c5imp
    real(8) :: yzz, yzzrefl, yzzphyssput, yizphyssput, yizchemsput
    real(8) :: factor

    ! *** Bulk neutrals ***

    c1blk = 0.075d0
    c5blk = c1blk * 0.02d0

    c3blk = 1.d0 / ( c1blk + c5blk )

    ! rGamm0 : Recycling rate of bulk neutrals
    rGamm0 = c1blk * c3blk
    if( rGamm0_in >= 0.d0 ) rGamm0 = rGamm0_in

    ! *** Impurity neutrals ***

    c1imp = 0.03d0
    c5imp = c1imp * 0.02d0

    ! ----- Self-sputtering -----

    yzzrefl     = 0.02d0
    yzzphyssput = 0.4d0
    yzz         = yzzrefl + yzzphyssput

    factor = c1imp / ( 1.d0 - ( 1.d0 - c1imp - c5imp ) * yzz )

    ! rGamm0zz : Recycling rate of impurity neutrals by self sputtering
    rGamm0zz = factor * yzz
    if( rGamm0zz_in >= 0.d0 ) rGamm0zz = rGamm0zz_in

    ! ----- Sputtering by bulk ions ---

    yizphyssput = 0.1d0
    yizchemsput = 0.05d0

    ! rGamm0zz : Recycling rate of impurity neutrals sputtered by bulk ions
    rGamm0iz = factor * ( yizphyssput + yizchemsput ) * c3blk * FSG0iz
    if( rGamm0iz_in >= 0.d0 ) rGamm0iz = rGamm0iz_in


!    write(6,*) rGamm0, rGamm0zz, rGamm0iz

  end subroutine tx_sol_particle_balance

end module tx_sol
