MODULE trcomm_globals
!     ****** GLOBAL VARIABLES ******
! TRGLB
  USE TRCOM0, ONLY: rkind, NFM, NSTM, NSM
  IMPLICIT NONE
  PUBLIC

  REAL(rkind)  ::  &
       WBULKT, WTAILT, WPT, AJT, AJOHT, AJNBT, AJRFT, AJBST, AJTTOR, &
       PINT, POHT, PNBT, PNFT, PBINT, PFINT, POUT, PCXT, PIET, &
       PRBT, PRCT, PRLT, PRSUMT, &
       PEXST, PRFST, SINT, SIET, SNBT, SNFT, SOUT, VLOOP, ALI, RQ1, &
       RPE, Q0, ZEFF0, QF, WPDOT, TAUE1, TAUE2, TAUE89, TAUE98, H98Y2, &
       BETAP0, BETAPA, BETA0, BETAA, BETAQ0, BETAN
  REAL(rkind), DIMENSION(:)  ,ALLOCATABLE :: &  ! (NSM)
       SPSCT
  REAL(rkind), DIMENSION(3)   :: &
       AJRFVT
  REAL(rkind), DIMENSION(NFM) :: &
       ANF0, TF0, ANFAV, TFAV, WFT
  REAL(rkind), DIMENSION(:)  ,ALLOCATABLE :: &  ! (NSTM)
       ANS0, TS0, ANSAV, ANLAV, TSAV, WST, PRFT, PBCLT, PFCLT, PLT, SPET, SLT
  REAL(rkind), DIMENSION(:,:),ALLOCATABLE :: &  ! (NSTM,3)
       PRFVT

CONTAINS

  SUBROUTINE allocate_trcomm_globals(ierr)
    USE TRCOM0, ONLY: NSM, NSTM
    INTEGER, INTENT(OUT) :: ierr
    ierr = 0
    ALLOCATE(SPSCT(NSM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(ANS0(NSTM),TS0(NSTM),ANSAV(NSTM),ANLAV(NSTM),TSAV(NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(WST(NSTM),PRFT(NSTM),PBCLT(NSTM),PFCLT(NSTM),STAT=ierr)
      IF(ierr /= 0) RETURN
    ALLOCATE(PLT(NSTM),SPET(NSTM),SLT(NSTM),PRFVT(NSTM,3),STAT=ierr)
      IF(ierr /= 0) RETURN
  END SUBROUTINE allocate_trcomm_globals

  SUBROUTINE deallocate_trcomm_globals
    DEALLOCATE(SPSCT)
    DEALLOCATE(ANS0,TS0,ANSAV,ANLAV,TSAV,WST,PRFT,PBCLT,PFCLT)
    DEALLOCATE(PLT,SPET,SLT,PRFVT)
  END SUBROUTINE deallocate_trcomm_globals

  SUBROUTINE deallocate_err_trcomm_globals
    IF(ALLOCATED(SPSCT)) DEALLOCATE(SPSCT)
    IF(ALLOCATED(ANS0 )) DEALLOCATE(ANS0 )
    IF(ALLOCATED(TS0  )) DEALLOCATE(TS0  )
    IF(ALLOCATED(ANSAV)) DEALLOCATE(ANSAV)
    IF(ALLOCATED(ANLAV)) DEALLOCATE(ANLAV)
    IF(ALLOCATED(TSAV )) DEALLOCATE(TSAV )
    IF(ALLOCATED(WST  )) DEALLOCATE(WST  )
    IF(ALLOCATED(PRFT )) DEALLOCATE(PRFT )
    IF(ALLOCATED(PBCLT)) DEALLOCATE(PBCLT)
    IF(ALLOCATED(PFCLT)) DEALLOCATE(PFCLT)
    IF(ALLOCATED(PLT  )) DEALLOCATE(PLT  )
    IF(ALLOCATED(SPET )) DEALLOCATE(SPET )
    IF(ALLOCATED(SLT  )) DEALLOCATE(SLT  )
    IF(ALLOCATED(PRFVT)) DEALLOCATE(PRFVT)
  END SUBROUTINE deallocate_err_trcomm_globals

END MODULE trcomm_globals
